### PR TITLE
Remove unnecessary empty lines

### PR DESCRIPTION
**Pull request by sampayo**
Removing unnecessary empty lines

From: 

```
    class SwimatTest {
        func swimatTest() -> Bool {
            return true
        }


        func swimatSecondTest() -> Bool {
            return true
        }


    }
```

To:

```
    class SwimatTest {
        func swimatTest() -> Bool {
            return true
        }

        func swimatSecondTest() -> Bool {
            return true
        }
    }
```

### CODE REVIEW

**Comment by Jintin** [comment]
Thanks for your great work.
Here are some point I think can improve.

isNextLineEmpty
isNextLineLowerBrackets
can change to `NSString: nextChar:(NSUInteger) index defaults:(unichar) value;`
to check the next char from index if you need.

isEmptyLine
can change to `NSString: lastNonSpaceIndex:(NSUInteger) index defaults:(NSUInteger) value;`
find the last non space char from end of string and check if '\n'

**Comment by Jintin** [comment]
One more thing is I use tab as indent by default.
It might not a standard, but it will much smooth if we use same indent.
If not it still ok. 
^^

**Comment by AaronBratcher** [comment]
Lines with only white space shouldn't have any white space really.

**Comment by Jintin** [comment]
In the first version, we skip the white space actually.
But one developer show me the message.
https://github.com/Jintin/Swimat/issues/16

It's also reasonable. So I changed.
If you very uncomfortable with it.
I think we can add preference to switch.

**Comment by sampayo** [comment]
Jintin, Thank you for the suggestion, I've just made these changes.

**Comment by Jintin** [comment]
You're welcome.
But I can't see your latest commit so far.

**Comment by sampayo** [comment]
It's the same commit. I added new changes to the old ones to have only one commit

**Comment by Jintin** [comment]
Maybe you should resend pull request.
I see no different with previous commit.
You can check the `File changed` tab

**Comment by sampayo** [comment]
I'm looking at it. I use the `tab` as indentation and I change the content of `isNextLineEmpty` and `isNextLineLowerBrackets` to use `NSString: nextNonSpaceIndex:(NSUInteger) index defaults:(unichar) value` and `isEmptyLine` to use`NSString: lastNonSpaceIndex:(NSUInteger) index defaults:(NSUInteger) value;`

The commit number is `4de6b61a2bdd1e5d9540aec5eef620d41d0f7733`

**Comment by Jintin** [comment]
Cool, so git can modify the remote commit?

**Pull request merged**
