### PR TITLE
New option: Remove/Force/Ignore line breaks before opening braces

### PR DESCRIPTION
**Pull request by raginmari**
Fixed issues introduced by #73.
Fixed bug in #93 

Improved tests. 

Updated README.

### CODE REVIEW

**Comment by Jintin** [comment]
Thank you.

**Comment by Jintin** [comment]
The unit test is fail, please take a look at it.
Thank you.
Corresponding commit : https://github.com/Jintin/Swimat/commit/42e6ffccb4c1045a84e8373188550f5d0ff99f31

**Comment by raginmari** [comment]
There are **two problems**:
- The failing tests are not very good because they test Swimat as a whole and not just the rule under test. I'll remove them and add further and better tests as necessary.
- The method `getIndentString` in `Prefs.m` does not return strings of whitespaces for INDENT_SPACE3 and INDENT_SPACE4. This error has been introduced in #91. I'll file a separate issue for that.

**Comment by raginmari** [comment]
Added a comment to #91.

**Comment by Jintin** [comment]
Thank you for your report.
It fix now. ^^

**Pull request merged**
