### PR TITLE
Add option for 3 space indents

### PR DESCRIPTION
**Pull request by reidmweber**

### CODE REVIEW

**Comment by Jintin** [comment]
Hi, thanks for contribute.
But we intend to merge pull request in dev branch for some reason.
Could you put this there.
Also I found you use three space in the pr too.
But it'll make some unnecessary diff in log, can you use tab as well?
Though it's not a standard, I hope we can have the same style. 
Thank you very much.

**Comment by Jintin** [comment]
Thank you very much.

**Comment by raginmari** [comment]
Indentation no longer works as expected. The method `getIndentString` in `Prefs.m` returns tabs for the settings `INDENT_SPACE3` and `INDENT_SPACE4`. Please fix this.

**Comment by Jintin** [comment]
Thank you for your report.
It fix now. ^^

**Pull request merged**
