### PR TITLE
Modularize testing (#4)

### PR DESCRIPTION
**Pull request by saagarjha**
Tests are now dynamically generated from a set of files instead of hard-coded
into the codebase

### CODE REVIEW

**Comment by Jintin** [comment]
It's wired that File change still a lot even I merge the previous pull request.

**Comment by saagarjha** [comment]
Hmm, that's odd. I've rebased this branch with yours and the diff looks more reasonable now.

**Comment by Jintin** [comment]
@saagarjha could you help with the failed test in travis?

**Comment by saagarjha** [comment]
Wut. I think I broke xcodebuild @Jintin:

> `<unknown>:0: error: unable to execute command: Segmentation fault: 11`

It works on my machine; could you try it on yours and merge it if it does?

**Comment by saagarjha** [comment]
@Jintin Nevermind, there was a bug in Xcode 8 that was breaking the build. I updated Xcode and the tests pass now so this should be ready to merge.

**Pull request merged**
