### PR TITLE
Signed XcodeKit.framework because xCode 12.2 requirement

### PR DESCRIPTION
**Pull request by firetrap**
Just added embedded and signed  XcodeKit.framework because xCode 12.2 requirement

### CODE REVIEW

**Comment by Jintin** [comment]
Thanks for your help.

**Comment by Jintin** [comment]
But interestingly after I use this config my Swimat is not showing for MacOS Catalina 10.15.7 (19H15) and Xcode 12.2 (12B45b) @firetrap

**Comment by Jintin** [comment]
#227 related issue.

**Comment by firetrap** [comment]
> But interestingly after I use this config my Swimat is not showing for MacOS Catalina 10.15.7 (19H15) and Xcode 12.2 (12B45b) @firetrap

Tomorrow I will take a look and try to help, but this doesn't make any sense because the embedded and sign already exists in Catalina the only change was optional and now is required in Big Sur.

**Comment by Jintin** [comment]
Thanks, the error seems to relate to this log just FYI, and sorry for duplicate message:
```
2020-11-20 09:13:12.715773+0800 Xcode[41471:2058752]  IDEExtensionManager: Xcode Extension does not incorporate XcodeKit: com.charcoaldesign.SwiftFormat-for-Xcode.SourceEditorExtension (file:///Applications/SwiftFormat%20for%20Xcode.app/Contents/PlugIns/SwiftFormat.appex/)
2020-11-20 09:13:12.720355+0800 Xcode[41471:2058752]  IDEExtensionManager: Xcode Extension does not incorporate XcodeKit: com.jintin.Swimat.Extension (file:///Applications/Swimat.app/Contents/PlugIns/Extension.appex/)
```

**Pull request merged**
