### PR TITLE
Improve Swimat.app with installation instructions

### PR DESCRIPTION
**Pull request by saagarjha**
Rename command line tool's name back to "swimat" and embed it in Swimat.app
Code sign command line tool on copy

### CODE REVIEW

**Comment by Jintin** [comment]
@saagarjha 
It's good but when I export using `Product -> Archive`, it turns out other items instead of macOS app.
How do you export to an .app file?

**Comment by Jintin** [comment]
Also can you help confirm this Archive is fine?
[Swimat.zip](https://github.com/Jintin/Swimat/files/714062/Swimat.zip)

**Comment by Jintin** [comment]
I'll temporary remove cli from app, so we can update app in the old way first.
Looking forward you next pull request.

**Comment by saagarjha** [comment]
Yes, your archive is fine. I've added a pull request (#142), which seems to build and archive fine on my machine.

**Pull request merged**
