### PR TITLE
Command Line Tool

### PR DESCRIPTION
**Pull request by saagarjha**
I've added an early version of a command line tool as a target.

### CODE REVIEW

**Comment by Jintin** [comment]
Thanks for your pr. Here is some suggestion may help.
1. for command line argument parser you can find some tool or try remove 'lookingForIndent' parameter. 
2. from now on, please use 4 space in code indent.
3. force is ambiguous, doesn't know why need.
4. `force = true` is better than `force = !force` if only call once.
5. too long line 62

``` swift
 if force || UTTypeCreatePreferredIdentifierForTag(kUTTagClassFilenameExtension, (file.pathExtension) as CFString, nil)?.takeRetainedValue() as? String ?? "" == "public.swift-source" {
```

**Comment by saagarjha** [comment]
1. A brief search turned up [this](https://github.com/jatoben/CommandLine).
2. Sure thing!
3. `force` is used to force formatting of files that don't "appear" to be Swift files; i.e. when the `UTTypeCreatePreferredIdentifierForTag` doesn't work. It's probably not worth including; I'll get rid of it. It was intended as a toggle (partly because I was too lazy to run through the arguments twice).

**Comment by Lutzifer** [comment]
I've had some good experiences using enums for command line arguments, instead of including something like CommandLine as dependency.

See https://github.com/Lutzifer/keyboardSwitcher/blob/master/keyboardSwitcher/CommandLineInterpreter.swift

**Comment by nebiros** [comment]
Any updates?, 😅

**Comment by saagarjha** [comment]
Oh, I've just been really busy in the last couple weeks. I'll get to it in a bit, when I have more time.

**Comment by saagarjha** [comment]
@Jintin I've added the changes you wanted.

**Comment by saagarjha** [comment]
@Jintin I've added the changes you wanted.

**Comment by Jintin** [comment]
I'll merge this change but give you some suggestions:
1. Target should be named `CommandLine` or something other than `swimat` because it's too general.
2. Usage is not clear, both in the command line and README.
3. Not support folder recursively format now.

I noticed you are a high school student, good job and keep going.
I like the `Options` idea.
Thanks for your contribution.

**Comment by saagarjha** [comment]
1. Sure, I'll rename it. I'd prefer `CommandLineTool` or `CLT` better, though–do you have any preference?
2. What kind of documentation does it need? There is a "helptext" when the command is used improperly, but I'm sure that it's not enough.
3. How exactly should recursive formatting work (I'm assuming this would use a `-r` option)? Does it go through the specified directories and format try to format every file it finds, and spit out warnings on non-Swift ones, only format files ending in `.swift`, or check the content UTI?

**Comment by Jintin** [comment]
1. Both great.
2. Take me as example: I didn't know how to provide a path to swimat at the first time. Also add -h support will be nice. I had some sample wrote myself before : [jgit](https://github.com/Jintin/jgit), [andle](https://github.com/Jintin/andle), [transai](https://github.com/Jintin/transai). You can take other great Command line tool as sample too.
3. If the path is folder you should recursively format file, if you want to more strictly add -r is not a bad idea.
4. `Extension` share some file with `CLI` if you like to, you can extract those file to another folder/group.

**Comment by saagarjha** [comment]
@Jintin Check out #134.

**Pull request merged**
