### PR TITLE
Updated README, suppressed logging in release builds

### PR DESCRIPTION
**Pull request by saagarjha**
Just some minor grammatical fixes and enabling logging only in debug builds…otherwise it spams the console, especially if “Format when Save” is on

### CODE REVIEW

**Comment by Jintin** [comment]
Thank you

**Comment by Jintin** [comment]
I didn't notice it will spam console, how do you find out that?

**Comment by saagarjha** [comment]
Check `/Applications/Utilities/Console.app`; that's where `NSLog`s go. [Here's](https://developer.apple.com/library/ios/technotes/tn2347/_index.html) some more info.

**Comment by Jintin** [comment]
Thanks a lot!

**Pull request merged**
