### PR TITLE
Fix issue with archiving

### PR DESCRIPTION
**Pull request by saagarjha**

### CODE REVIEW

**Comment by Jintin** [comment]
It wired that you have c6e11cb4ed0c02fdead1667c0834ab9c76dd63b8 and 7fc9dc411afd4bc0d50d2a0ae6413cfd0b64bb21 commit. In fact you have to do revert commit with c6e11cb4ed0c02fdead1667c0834ab9c76dd63b8. Maybe you can try rebase next time.

**Comment by Jintin** [comment]
And maybe we can try to integrate with `homebrew`. It's more natural than open app to install a command line tool.

**Comment by saagarjha** [comment]
Oops, it looks like I forgot to pull the recent changes. As for bundling a command line tool with the app, I know a couple of apps that do it–for example, Github Desktop, Hopper Disassembler, Sublime Text, etc. all have an executable in their main app. I do agree, however, with the idea of adding Swimat to homebrew. I'll look into it.

**Comment by saagarjha** [comment]
I've taken a look at getting Swimat on Homebrew (instructions available [here](http://docs.brew.sh/Formula-Cookbook.html)). There's a couple of things we need to do before we can set it up:

1. We need a new release containing the changes I made (otherwise it will fail to compile)
2. We need some Swimat test cases for the post-install checks, just to make sure it's running properly
3. We need a bit of info for swimat.rb (which I've been working on, in italics; tell me what you think):

```ruby
class Swimat < Formula
  desc "Command Line Tool to help format Swift code"
  homepage "https://github.com/Jintin/Swimat" # Unless you have a real homepage?
  url "https://github.com/Jintin/Swimat.git"
  sha256 "08876d0c13fc7782ada2cd2bbbf9724399ccea216caee0cfaf2acf298eb5b3ac"
  head "https://github.com/Jintin/Swimat.git"

  depends_on :xcode => "8.0"

  def install
    xcodebuild "-project", "Swimat.xcodeproj", "-scheme", "CLI", "-configuration", "Release", "SYMROOT=build"
  end

  test do
     # We need something here
  end
end
```

**Comment by saagarjha** [comment]
@Jintin Sorry to bother you, but would you mind making a release with these changes?

**Comment by Jintin** [comment]
Sure. 
After I read the document of `homebrew` I think maybe the current way(imbedded) is better.
What do you think?

**Comment by Jintin** [comment]
Maybe this topic can fire a new issue to let more people participate.

**Comment by Jintin** [comment]
FYI
https://github.com/Jintin/Swimat/releases/tag/v1.2.1

**Comment by saagarjha** [comment]
Thanks. I've submitted pull requests:
* [Homebrew](https://github.com/Homebrew/homebrew-core/pull/9119) *Merged*
* [Homebrew Cask](https://github.com/caskroom/homebrew-cask/pull/29258) *Merged*

Also, have you considered making Swimat available on the App Store?

**Comment by Jintin** [comment]
screen shot 2017-01-20 at 10 59 46 pm
Sure, after you update our app view controller.
But the `app id` seems have conflict problem.
I've already send to Apple to find out solution.

You are such a productive person.

BTW, I found `Atom` is able bind the app with the command line tool.
So after I install from `brew cask` the command line tool is installed.
And delete will remove it also.
Would you like to study how dose `Atom` do?

**Comment by saagarjha** [comment]
> You are such a productive person.

Why, thank you! I'm not sure if it's the same in Taiwan, but in the U.S. people tend to have a lot of free time after submitting college applications.

As for the installation procedures, here's how I'm visualizing it (I'm planning to add this to the README.md when I update .travis.yml in a bit):

* Command Line Tool (installed to `/usr/local/bin/` in all cases) available from:
    * Build from source
    * Homebrew (`brew install swimat`)
    * Github releases, press install button in-app
    * Homebrew Cask, press install button in-app (`brew cask install swimat`)
* Xcode Source Editor Extension (with Command Line Tool by pressing install button in-app) available from:
    * Build from source
    * Mac App Store (sans Command Line Tools, see below)
    * Github releases
    * Homebrew Cask (`brew cask install swimat`)

We'll need to remove the `swimat` command line tool from the app bundle for the Mac App Store version, as per [Apple's Guidelines](https://developer.apple.com/app-store/review/guidelines/), since writing to `/usr/local/bin/` may require administrator approval:

> They may not request escalation to root privileges or use setuid attributes.

I'll work on creating a special scheme for App Store distribution that doesn't include the binary.

Atom, by the way, [symlinks its binaries](https://github.com/atom/atom/blob/7929e261a0d6e78ff4ca5196c8b385946e64dbd9/src/command-installer.coffee) to `/usr/local/bin/` just as we do (but in CoffeeScript instead of AppleScript).

**Comment by Jintin** [comment]
What I mean is if we can bind app with command line tool like `Atom`, we don't need to add button in App to prompt install. And also no need to integrate with `Homebrew`.

Since the Mac App Store is an option for me, we can decide it later if it has limitation.

And for traditional Asian student, I think we spend more time in schoolwork.

**Pull request merged**
